name: tests-auth

on:
  pull_request:
    pahts:
      - 'auth/**'
  
jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm install && npm run test:ci
